### ISSUE TITLE
[[A#title]] Redirection issues

### ISSUE THREAD

**Issue by TomIsFat** [1C0D/Obsidian-Close-Similar-Tabs#12]
Let’s assume that we have a document called A that has the following format:

```md
### title1

### title2
some valuable information here
```
If I want to cite title2, I would create a link like this: [[A#title2]]. When the A document is opened, clicking on this redirection link, the plugin will automatically block you from moving to the ###title2 location.

This issue is very evident in documents that have several subheadings, and the normal redirection does not work.

**Comment by 1C0D** [comment]
It's solved with the new version, which is a total refactory

**Comment by TomIsFat** [comment]
solved

**Comment by distbit0** [comment]
I am having a very similar issue, which unfortunately is not addressed by the latest update.

Scenario:
Document A contains headings b and c
Document A is currently open in a tab at heading b
I click on link to A#c using keyboard shortcut ctrl+enter (opens link in new tab)
Document A is opened in a new tab at heading c, but then this tab is immediately closed by Close Similar Tabs
I am redirected by Close Similar Tabs to Document A at heading b (the original tab where document A is open)

What I would like is to end up on Document A but on heading c rather than heading b, while still only having one tab containing Document A.

Many thx!! @1C0D

**Comment by 1C0D** [comment]
just to tell I saw your issue but for the moment I get no answer to this problem.
