### ISSUE TITLE
Bug: Incompatible with the 'Hover Editor' plugin.

### ISSUE THREAD

**Issue by zhaihao** [1C0D/Obsidian-Close-Similar-Tabs#16]
In v2.0.0，If I open a page A, using 'Hover Editor' to view A page will result in the closure of page A.

in v1.7.3，everything works very well

**Comment by 1C0D** [comment]
do you mean doing this?
![image](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/assets/63018905/935d1e17-d02f-42ec-8e2f-d1c94f2a0030)

**Comment by 1C0D** [comment]
Ah ok that's a plugin. I will watch this

**Comment by 1C0D** [comment]
Ok I published the new version. With this fix and some other

**Comment by 1C0D** [comment]
Thank you

**Comment by alexinea** [comment]
In version 2.3.1, there is again an incompatibility issue with the Hover Editor. When this plugin is enabled and the note is previewed using the Hover Editor, the preview box displays the default page instead of the content of the note.

![image](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/assets/980129/6cf19296-7a27-4939-bbaf-03fcf411ef9a)
When `obsidian-close-similar-tabs` is enabled.


![image](https://github.com/1C0D/Obsidian-Close-Similar-Tabs/assets/980129/c24a8f0a-c81b-4f3d-8f21-6fa37325c840)
When `obsidian-close-similar-tabs` is disabled.

**Comment by 1C0D** [comment]
sry broke this again as I reorganized all logic. fixing it
